### ISSUE TITLE
Failed to inference with onnxconverter-common==1.7.0

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/yolov3-face#5]
```
Using TensorFlow backend.
2020-09-24 10:20:10.442204: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
classes 1
Traceback (most recent call last):
  File "inference.py", line 151, in <module>
    detect_img(YOLO(sys.argv[2]), sys.argv[3], sys.argv[4], model_file_name)
  File "inference.py", line 134, in detect_img
    yolo.session = onnxruntime.InferenceSession(model_file_name)
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (concatenate_1) Op (Concat) [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=1 Target=2 Dimension=1
```

**Comment by kyakuno** [comment]
We must use onnxconverter-common==1.6.0.

**Comment by kyakuno** [comment]
Reference : https://qiita.com/tfukumori/items/66966074b746bc815f18
